export const About_us = "/Aboutus"
export const Home_page = "/Home"
// export const Login_box = "/login"
// export const Booking_box = "/booking"
// export const Setting_box = "/setting"
// export const Last_page = "/last"
// export const Home_page = "/home"
// export const VIEW_TEMPLE = "/view_temple"
// export const VIEW_BLOGS = "/blogs"
// export const BADRI_NATH = "/badrinath_temple"
// export const VIEW_BOOKING = "/view_booking"

